"use strict";jQuery.fn.cspt_is_bound=function(type){if(this.data('events')!==undefined){if(this.data('events')[type]===undefined||this.data('events')[type].length===0){return!1}
return(-1!==$.inArray(fn,this.data('events')[type]))}else{return!1}};var cspt_sticky_header=function(){if(jQuery('.cspt-header-sticky-yes').length>0){var header_html=jQuery('#masthead .cspt-header-inner').html();jQuery('.cspt-sticky-header').append(header_html);jQuery('.cspt-sticky-header .main-navigation ul, .cspt-sticky-header .main-navigation ul li, .cspt-sticky-header .main-navigation ul li a').removeAttr('id');jQuery('.cspt-sticky-header h1').each(function(){var thisele=jQuery(this);var thisele_class=jQuery(this).attr('class');thisele.replaceWith('<span class="'+thisele_class+'">'+jQuery(thisele).html()+'</span>')});if(jQuery('.cspt-header-inner').hasClass('cspt-infostack-header')){jQuery(".cspt-sticky-header .cspt-header-menu-area").insertAfter(".cspt-sticky-header .site-branding");jQuery('.cspt-sticky-header .cspt-header-info, .cspt-sticky-header .cspt-mobile-search, .cspt-sticky-header .cspt-social-links').remove()}}}
var cspt_sticky_header_class=function(){if(jQuery('#wpadminbar').length>0){jQuery('#masthead').addClass('cspt-adminbar-exists')}
var offset_px=300;if(jQuery('.cspt-header-inner').length>0){offset_px=jQuery('.cspt-header-inner').height()+offset_px}
if(jQuery(window).scrollTop()>offset_px){jQuery('#masthead').addClass('cspt-fixed-header');jQuery('.cspt-sticky-header .mega-menu.max-mega-menu.mega-menu-horizontal').attr("id","mega-menu-creativesplanet-top")}else{jQuery('#masthead').removeClass('cspt-fixed-header')}
jQuery(window).scroll(function(){if(jQuery(window).scrollTop()>offset_px){jQuery('#masthead').addClass('cspt-fixed-header');jQuery('.cspt-sticky-header .mega-menu.max-mega-menu.mega-menu-horizontal').attr("id","mega-menu-creativesplanet-top")}else{jQuery('#masthead').removeClass('cspt-fixed-header')}})}
var cspt_toggleSidebar=function(){jQuery('#menu-toggle').on('click',function(){console.log('Clicked_11');jQuery("body:not(.mega-menu-creativesplanet-top) .cspt-navbar > div, body:not(.mega-menu-creativesplanet-top)").toggleClass("active")})
if(jQuery('.cspt-navbar > div > .closepanel').length==0){jQuery('.cspt-navbar > div').append('<span class="closepanel"><i class="cspt-base-icon-cancel"></i></span>');jQuery('.cspt-navbar > div > .closepanel, .mega-menu-creativesplanet-top .nav-menu-toggle').on('click',function(){jQuery(".cspt-navbar > div, body, .mega-menu-wrap").toggleClass("active")});if(jQuery('.cspt-header-inner .cspt-search-cart-box > .cspt-cart-wrapper').length>0){if(jQuery('.cspt-navbar > div > .cspt-responsive-icons').length==0){jQuery('.cspt-navbar > div').append("<div class='cspt-responsive-icons'></div>")}
jQuery('.cspt-navbar > div > .cspt-responsive-icons').append('<div class="cspt-cart-wrapper"></div>');jQuery('.cspt-navbar > div > .cspt-responsive-icons .cspt-cart-wrapper').append(jQuery('.cspt-header-inner .cspt-search-cart-box > .cspt-cart-wrapper').html())}
if(jQuery('.cspt-header-inner .cspt-search-cart-box > .cspt-header-search-btn').length>0){if(jQuery('.cspt-navbar > div > .cspt-responsive-icons').length==0){jQuery('.cspt-navbar > div').append("<div class='cspt-responsive-icons'></div>")}
jQuery('.cspt-navbar > div > .cspt-responsive-icons').append('<div class="cspt-header-search-btn"></div>');jQuery('.cspt-navbar > div > .cspt-responsive-icons .cspt-header-search-btn').append(jQuery('.cspt-header-inner .cspt-search-cart-box > .cspt-header-search-btn').html())}
return!1}}
var creativesplanet_stretched_col_calc=function(){if(jQuery('.wpb_column.cspt-col-stretched-yes').length>0){var window_width=jQuery(window).width();var document_width=jQuery(document).width();jQuery('.wpb_column.cspt-col-stretched-yes').each(function(){var this_ele=jQuery(this);var main_width=jQuery('#main').width();var extra_width=((window_width-main_width)/2);var curr_width=jQuery('.wpb_wrapper',this_ele).width();var wrapper_div='';var minimum_width=0;var both_margin=!1;if(this_ele.parent().hasClass('cspt-break-col-1200')){minimum_width=1200}else if(this_ele.parent().hasClass('cspt-break-col-991')){minimum_width=991}else if(this_ele.parent().hasClass('cspt-break-col-767')){minimum_width=767}
if(minimum_width>0&&document_width<minimum_width){both_margin=!0}
if(this_ele.hasClass('cspt-col-stretched-right')){if(this_ele.hasClass('cspt-col-stretched-content-yes')){wrapper_div=', .vc_column-inner > .wpb_wrapper'}
jQuery('.vc_column-inner > .cspt-stretched-div'+wrapper_div,this_ele).css('margin-right','-'+extra_width+'px');if(both_margin==!0){jQuery('.vc_column-inner > .cspt-stretched-div'+wrapper_div,this_ele).css('margin-left','-'+extra_width+'px')}else{jQuery('.vc_column-inner > .cspt-stretched-div'+wrapper_div,this_ele).css('margin-left','')}}else{if(this_ele.hasClass('cspt-col-stretched-content-yes')){wrapper_div=', .vc_column-inner > .wpb_wrapper'}
jQuery('.vc_column-inner > .cspt-stretched-div'+wrapper_div,this_ele).css('margin-left','-'+extra_width+'px');if(both_margin==!0){jQuery('.vc_column-inner > .cspt-stretched-div'+wrapper_div,this_ele).css('margin-right','-'+extra_width+'px')}else{jQuery('.vc_column-inner > .cspt-stretched-div'+wrapper_div,this_ele).css('margin-right','')}}})}}
var cspt_circle_progressbar=function(){jQuery('.cspt-circle-outer').each(function(){var this_circle=jQuery(this);var emptyFill_val="rgba(0, 0, 0, 0)";var thickness_val=10;var fill_val=this_circle.data('fill');if(typeof this_circle.data('emptyfill')!=='undefined'&&this_circle.data('emptyfill')!=''){emptyFill_val=this_circle.data('emptyfill')}
if(typeof this_circle.data('thickness')!=='undefined'&&this_circle.data('thickness')!=''){thickness_val=this_circle.data('thickness')}
if(typeof this_circle.data('filltype')!=='undefined'&&this_circle.data('filltype')=='gradient'){fill_val={gradient:[this_circle.data('gradient1'),this_circle.data('gradient2')],gradientAngle:Math.PI/4}}
if(typeof jQuery.fn.circleProgress=="function"){var digit=this_circle.data('digit');var before=this_circle.data('before');var after=this_circle.data('after');var c_width=this_circle.data('width');var digit=Number(digit);var short_digit=(digit/100);jQuery('.cspt-circle',this_circle).circleProgress({value:0,size:c_width,startAngle:-Math.PI/4*2,thickness:thickness_val,emptyFill:emptyFill_val,fill:fill_val}).on('circle-animation-progress',function(event,progress,stepValue){this_circle.find('.cspt-circle-number').html(before+Math.round(stepValue*100)+after)})}
this_circle.waypoint(function(direction){if(!this_circle.hasClass('completed')){if(typeof jQuery.fn.circleProgress=="function"){jQuery('.cspt-circle',this_circle).circleProgress({value:short_digit})};this_circle.addClass('completed')}},{offset:'85%'})})}
var cspt_progressbar=function(){jQuery('.cspt-progressbar').each(function(){var $progressbar_ele=jQuery(this);jQuery(this).waypoint(function(direction){var $progressbar=jQuery('.elementor-progress-bar',$progressbar_ele);if(!$progressbar.hasClass('completed')){$progressbar.css('width',$progressbar.data('max')+'%').addClass('completed')}},{offset:'99%'})})}
var cspt_carousel=function(){jQuery(".creativesplanet-element-viewtype-carousel").each(function(){var carouselElement=jQuery(this);jQuery('.cspt-ele',carouselElement).removeClass(function(index,className){return(className.match(/(^|\s)col-md-\S+/g)||[]).join(' ')}).removeClass(function(index,className){return(className.match(/(^|\s)col-lg-\S+/g)||[]).join(' ')});var columns=jQuery(this).data('columns');var loop=jQuery(this).data('loop');if(columns=='1'){var responsive_items=['1','1','1','1','1']}else if(columns=='2'){var responsive_items=['2','2','2','2','1']}else if(columns=='3'){var responsive_items=['3','2','2','2','1']}else if(columns=='4'){var responsive_items=['4','4','3','2','1']}else if(columns=='5'){var responsive_items=['5','4','3','2','1']}else if(columns=='6'){var responsive_items=['6','4','3','2','1']}else{var responsive_items=['3','3','3','2','1']}
var margin_val=30;if(jQuery(carouselElement).data('margin')!=''){margin_val=jQuery(carouselElement).data('margin')}
var posts_wrapper_class='.cspt-element-posts-wrapper';var val_nav=jQuery(carouselElement).data('nav');if(val_nav=='above'){val_nav=!1}
var car_options={loop:jQuery(carouselElement).data('loop'),autoplay:jQuery(carouselElement).data('autoplay'),center:jQuery(carouselElement).data('center'),nav:val_nav,dots:jQuery(carouselElement).data('dots'),autoplaySpeed:jQuery(carouselElement).data('autoplayspeed'),autoplayTimeout:jQuery(carouselElement).data('autoplayspeed')+5000,navSpeed:jQuery(carouselElement).data('autoplayspeed'),dotsSpeed:jQuery(carouselElement).data('autoplayspeed'),dragEndSpeed:jQuery(carouselElement).data('autoplayspeed'),margin:30,items:columns,responsiveClass:!0,responsive:{1199:{items:responsive_items[0],},991:{items:responsive_items[1],},767:{items:responsive_items[2],},575:{items:responsive_items[3],},0:{items:responsive_items[4],}}};if(typeof margin_val=="string"&&margin_val!=''){margin_val=margin_val.replace('px','');margin_val=parseInt(margin_val);car_options.margin=margin_val}
var cspt_owl=jQuery(posts_wrapper_class,carouselElement).removeClass('row multi-columns-row').addClass('owl-carousel').owlCarousel(car_options);jQuery('.cspt-carousel-prev',carouselElement).click(function(event){event.preventDefault();cspt_owl.trigger('prev.owl.carousel',[jQuery(carouselElement).data('autoplayspeed')])});jQuery('.cspt-carousel-next',carouselElement).click(function(event){event.preventDefault();cspt_owl.trigger('next.owl.carousel',[jQuery(carouselElement).data('autoplayspeed')])})})};var cspt_sorting=function(){jQuery('.cspt-sortable-yes').each(function(){var boxes=jQuery('.cspt-element-posts-wrapper',this);var links=jQuery('.cspt-sortable-list a',this);boxes.isotope({animationEngine:'best-available'});links.on('click',function(e){var selector=jQuery(this).data('sortby');if(selector!='*'){var selector='.'+selector}
boxes.isotope({filter:selector,itemSelector:'.cspt-ele',layoutMode:'fitRows'});links.removeClass('cspt-selected');jQuery(this).addClass('cspt-selected');e.preventDefault()})})}
var cspt_back_to_top=function(){var btn=jQuery('.scroll-to-top');jQuery(window).scroll(function(){if(jQuery(window).scrollTop()>300){btn.addClass('show')}else{btn.removeClass('show')}});btn.on('click',function(e){e.preventDefault();jQuery('html, body').animate({scrollTop:0},'300')})}
var cspt_navbar=function(){if(!jQuery('ul#cspt-top-menu > li > a[href="#"]').cspt_is_bound('click')){jQuery('ul#cspt-top-menu > li > a[href="#"]').click(function(){return!1})}
jQuery('.cspt-navbar > div > ul li:has(ul)').append("<span class='sub-menu-toggle'><i class='cspt-base-icon-down-open-big'></i></span>");jQuery('.cspt-navbar li').on('hover',function(){if(jQuery(this).children("ul").length==1){var parent=jQuery(this);var child_menu=jQuery(this).children("ul");if(jQuery(parent).offset().left+jQuery(parent).width()+jQuery(child_menu).width()>jQuery(window).width()){jQuery(child_menu).addClass('cspt-nav-left')}else{jQuery(child_menu).removeClass('cspt-nav-left')}}});jQuery('.sub-menu-toggle').on('click',function(){if(jQuery(this).siblings('.sub-menu, .children').hasClass('show')){jQuery(this).siblings('.sub-menu, .children').removeClass('show');jQuery('i',jQuery(this)).removeClass('cspt-base-icon-up-open-big').addClass('cspt-base-icon-down-open-big')}else{jQuery(this).siblings('.sub-menu, .children').addClass('show');jQuery('i',jQuery(this)).removeClass('cspt-base-icon-down-open-big').addClass('cspt-base-icon-up-open-big')}
return!1});jQuery('.cspt-navbar ul.menu > li > a').on('click',function(){if(jQuery(this).attr('href')=='#'&&jQuery(this).siblings('ul.sub-menu, ul.children').length>0){jQuery(this).siblings('.sub-menu-toggle').trigger('click');return!1}})}
var cspt_lightbox=function(){var i_type='image';jQuery('a.cspt-lightbox, a.cspt-lightbox-video, .cspt-lightbox-video a, .cspt-lightbox a').each(function(){if(jQuery(this).hasClass('cspt-lightbox-video')||jQuery(this).closest('.wpb_single_image').hasClass('cspt-lightbox-video')||jQuery(this).closest('.vc_icon_element').hasClass('cspt-lightbox-video')||jQuery(this).closest('.vc_custom_heading').hasClass('cspt-lightbox-video')||jQuery(this).closest('.cspt-ihbox').hasClass('cspt-lightbox-video')||jQuery(this).closest('.elementor-widget-icon').hasClass('cspt-lightbox-video')||jQuery(this).closest('.elementor-widget-heading').hasClass('cspt-lightbox-video')||jQuery(this).closest('.elementor-widget-cspt_icon_heading').hasClass('cspt-lightbox-video')){i_type='iframe'}else{i_type='image'}
jQuery(this).magnificPopup({type:i_type})})}
var cspt_video_popup=function(){jQuery('.cspt-popup').on('click',function(event){event.preventDefault();var href=jQuery(this).attr('href');var title=jQuery(this).attr('title');window.open(href,title,"width=600,height=500")})}
var cspt_testimonial=function(){jQuery('.cspt-testimonial-active').each(function(){var ele_parent=jQuery(this).closest('.cspt-element-posts-wrapper');jQuery('.creativesplanet-ele.creativesplanet-ele-testimonial',ele_parent).on('mouseover',function(){jQuery('.creativesplanet-ele.creativesplanet-ele-testimonial',ele_parent).removeClass('cspt-testimonial-active');jQuery(this).addClass('cspt-testimonial-active')})})}
var cspt_search_btn=function(){jQuery(function(){jQuery('.cspt-header-search-btn').on("click",function(event){event.preventDefault();jQuery(".cspt-header-search-form-wrapper").addClass("open");jQuery('.cspt-header-search-form-wrapper input[type="search"]').focus()});jQuery(".cspt-search-close").on("click keyup",function(event){jQuery(".cspt-header-search-form-wrapper").removeClass("open")})})}
var cspt_gallery=function(){jQuery("div.cspt-gallery").each(function(){jQuery(this).lightSlider({item:1,auto:!0,loop:!0,controls:!1,speed:1500,pause:5500})})}
var cspt_center_logo_header_class=function(){if(jQuery('#masthead.cspt-header-style-5 ul#cspt-top-menu').length>0){var has_class=jQuery('#masthead.cspt-header-style-5 ul#cspt-top-menu > li').hasClass('cspt-logo-append');if(has_class==!1){var total_li=jQuery('#masthead.cspt-header-style-5 ul#cspt-top-menu > li').length;var li=Math.floor(total_li/2);jQuery('#masthead.cspt-header-style-5 ul#cspt-top-menu > li:nth-child('+li+')').addClass('cspt-logo-append')}}}
var cspt_selectwrap=function(){jQuery("select:not(#rating)").each(function(){jQuery(this).wrap("<div class='cspt-select'></div>")})}
var cspt_preloader=function(){jQuery(".cspt-preloader").fadeOut('600')}
var creativesplanet_set_portfolio_right_column=function(){setTimeout(function(){jQuery('.cspt-element-portfolio-style-5').each(function(){var thisele=jQuery(this);if(jQuery(this).closest('.elementor-element.elementor-section-stretched.elementor-section-full_width')){var body_width=jQuery('body').outerWidth();var container_width=jQuery('.creativesplanet-container',thisele).outerWidth();var padding_left=(body_width-container_width)/2;jQuery('.creativesplanet-portfolio-expand-right',thisele).css('padding-left',padding_left)}})})}
var creativesplanet_set_service_right_column=function(){setTimeout(function(){jQuery('.cspt-element-service-style-8 ,.cspt-element-service-style-9').each(function(){var thisele=jQuery(this);if(jQuery(this).closest('.elementor-element.elementor-section-stretched.elementor-section-full_width')){var body_width=jQuery('body').outerWidth();var container_width=jQuery('.creativesplanet-container',thisele).outerWidth();var padding_left=(body_width-container_width)/2;jQuery('.creativesplanet-service-expand-right',thisele).css('padding-left',padding_left)}})})}
var cspt_validate=function(){jQuery("#commentform").submit(function(event){var error=!1;jQuery('.cspt-form-error').hide();if(jQuery("#author").length>0&&!jQuery("#author").val()){jQuery('.comment-form-author .cspt-form-error').show();error=!0}
if(jQuery("#comment").length>0&&!jQuery("#comment").val()){jQuery('.comment-form-comment .cspt-form-error').show();error=!0}
if(jQuery("#email").length>0){if(!jQuery("#email").val()){jQuery('.comment-form-email .cspt-form-error.cspt-empty-email').show();error=!0}else{var valid_email=(/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/.test(jQuery("#email").val()));if(valid_email!=!0){jQuery('.comment-form-email .cspt-form-error.cspt-invalid-email').show();error=!0}}}
if(error==!0){event.preventDefault();return!1}else{return!0}})}
jQuery(document).ready(function(){cspt_toggleSidebar();cspt_validate();creativesplanet_set_portfolio_right_column();creativesplanet_set_service_right_column();setTimeout(function(){cspt_carousel()},100);cspt_sorting();creativesplanet_stretched_col_calc();cspt_back_to_top();cspt_sticky_header();cspt_navbar();cspt_lightbox();cspt_video_popup();cspt_testimonial();cspt_search_btn();cspt_center_logo_header_class();cspt_selectwrap();cspt_progressbar();cspt_sticky_header_class()});jQuery(window).on('load',function(){cspt_preloader();cspt_sorting();cspt_gallery()});jQuery(window).resize(function(){creativesplanet_set_portfolio_right_column();creativesplanet_set_service_right_column()})